# Generated by Django 4.2.2 on 2023-06-29 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0002_alter_advertisement_image_alter_article_image_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(upload_to='images/advertisements/%Y/%m/%d/kg1TTtv4zd7QN5AO8mMXAfeqRb7PzS.jpg', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='images/articles/%Y/%m/%d/TytfTTNZNisRPGOOn5ZSme0GypU3c0.jpg', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='Сommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Дата написания')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Общение',
            },
        ),
    ]
