# Generated by Django 4.2.2 on 2023-06-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_advertisement_image_alter_article_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(upload_to='images/advertisements/%Y/%m/%d/sLQme5QJQhFTzwZKI6lPywYdvGmZU4.jpg', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='images/articles/%Y/%m/%d/dCIoVmEdnIAvKd678DF3wUtka2eU4Z.jpg', verbose_name='Изображение'),
        ),
    ]
